export const ErrorCode = {
  // Technical (repository / infra)
  DB_CONNECTION_FAILED: "DB_CONNECTION_FAILED",
  DB_UNIQUE_VIOLATION: "DB_UNIQUE_VIOLATION",
  DB_FOREIGN_KEY_VIOLATION: "DB_FOREIGN_KEY_VIOLATION",
  DB_NOT_NULL_VIOLATION: "DB_NOT_NULL_VIOLATION",
  DB_QUERY_FAILED: "DB_QUERY_FAILED",
  EMAIL_SEND_FAILED: "EMAIL_SEND_FAILED",

  // Application / domain (service)
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  FORBIDDEN: "FORBIDDEN",
  UNAUTHORIZED: "UNAUTHORIZED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  INTERNAL_ERROR: "INTERNAL_ERROR",

  // Authentication
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  USER_INACTIVE: "USER_INACTIVE",
  USER_SUSPENDED: "USER_SUSPENDED",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  CLINIC_REQUIRED: "CLINIC_REQUIRED",
  MEMBERSHIP_NOT_FOUND: "MEMBERSHIP_NOT_FOUND",
  MEMBERSHIP_INACTIVE: "MEMBERSHIP_INACTIVE",
  SUBSCRIPTION_INACTIVE: "SUBSCRIPTION_INACTIVE",
  PLAN_LIMIT_EXCEEDED: "PLAN_LIMIT_EXCEEDED",
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  PASSWORD_CHANGE_REQUIRED: "PASSWORD_CHANGE_REQUIRED",

  // Users / invitations
  INVITATION_NOT_FOUND: "INVITATION_NOT_FOUND",
  INVITATION_REVOKED: "INVITATION_REVOKED",
  INVITATION_ALREADY_ACCEPTED: "INVITATION_ALREADY_ACCEPTED",
  INVITE_EMAIL_MISMATCH: "INVITE_EMAIL_MISMATCH",

  // Appointments / availability
  /** Professional already has an overlapping active appointment. */
  APPOINTMENT_SLOT_UNAVAILABLE: "APPOINTMENT_SLOT_UNAVAILABLE",
  /**
   * Requested slot is outside clinic business hours.
   * Code name kept for compatibility; message refers to the clinic.
   */
  PROFESSIONAL_OUTSIDE_WORKING_HOURS: "PROFESSIONAL_OUTSIDE_WORKING_HOURS",
} as const

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode]
