export const ErrorCode = {
  // Technical (repository / infra)
  DB_CONNECTION_FAILED: "DB_CONNECTION_FAILED",
  DB_UNIQUE_VIOLATION: "DB_UNIQUE_VIOLATION",
  DB_FOREIGN_KEY_VIOLATION: "DB_FOREIGN_KEY_VIOLATION",
  DB_NOT_NULL_VIOLATION: "DB_NOT_NULL_VIOLATION",
  DB_QUERY_FAILED: "DB_QUERY_FAILED",
  EMAIL_SEND_FAILED: "EMAIL_SEND_FAILED",

  // Application / domain (service)
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  FORBIDDEN: "FORBIDDEN",
  UNAUTHORIZED: "UNAUTHORIZED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  INTERNAL_ERROR: "INTERNAL_ERROR",

  // Authentication
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  USER_INACTIVE: "USER_INACTIVE",
  USER_SUSPENDED: "USER_SUSPENDED",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  CLINIC_REQUIRED: "CLINIC_REQUIRED",
  MEMBERSHIP_NOT_FOUND: "MEMBERSHIP_NOT_FOUND",
  MEMBERSHIP_INACTIVE: "MEMBERSHIP_INACTIVE",
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
} as const

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode]
