export const routes = {
  landing: "/",
  login: "/login",
  signUp: "/sign-up",
  forgotPassword: "/forgot-password",
  verifyEmail: "/verify-email",
  changePassword: "/change-password",
  invite: "/invite",
  professionalInvite: "/invite/professional",
  onboardingPlan: "/onboarding/plan",
  onboardingClinic: "/onboarding/clinic",
  onboardingHours: "/onboarding/hours",
  membershipInactive: "/membership-inactive",
  selectClinic: "/select-clinic",
  home: "/home",
  users: "/users",
  patients: "/patients",
  professionals: "/professionals",
  appointments: "/appointments",
  settings: "/settings",
  settingsGeneral: "/settings/general",
  settingsHours: "/settings/hours",
  settingsDanger: "/settings/danger",
  /** Placeholder until the help page exists. */
  help: "/help",
} as const
