export const AUDIT_ACTIONS = {
  PATIENT_CREATE: "patient.create",
  PATIENT_UPDATE: "patient.update",
  PATIENT_DELETE: "patient.delete",
  APPOINTMENT_CREATE: "appointment.create",
  APPOINTMENT_RESCHEDULE: "appointment.reschedule",
  APPOINTMENT_UPDATE: "appointment.update",
  APPOINTMENT_STATUS_UPDATE: "appointment.status_update",
  APPOINTMENT_CANCEL: "appointment.cancel",
  CLINIC_CREATE: "clinic.create",
  CLINIC_UPDATE: "clinic.update",
  CLINIC_DELETE: "clinic.delete",
  CLINIC_HOURS_UPSERT: "clinic_hours.upsert",
  MEMBER_ROLE_UPDATE: "member.role_update",
  MEMBER_REMOVE: "member.remove",
  MEMBER_STATUS_UPDATE: "member.status_update",
  INVITATION_CREATE: "invitation.create",
  INVITATION_REVOKE: "invitation.revoke",
  INVITATION_ACCEPT: "invitation.accept",
  CHARGE_CREATE: "charge.create",
  CHARGE_MARK_PAID: "charge.mark_paid",
  CHARGE_CANCEL: "charge.cancel",
  CLINICAL_NOTE_UPSERT: "clinical_note.upsert",
  VITAL_SIGNS_UPSERT: "vital_signs.upsert",
  CLINICAL_ALERT_CREATE: "clinical_alert.create",
  CLINICAL_ALERT_DELETE: "clinical_alert.delete",
  PRESCRIPTION_CREATE: "prescription.create",
  PRESCRIPTION_UPDATE: "prescription.update",
  PRESCRIPTION_ISSUE: "prescription.issue",
  PRESCRIPTION_DELETE: "prescription.delete",
  PRESCRIPTION_LAYOUT_UPSERT: "prescription_layout.upsert",
  PRESCRIPTION_LAYOUT_CREATE: "prescription_layout.create",
  PRESCRIPTION_LAYOUT_UPDATE: "prescription_layout.update",
  PRESCRIPTION_LAYOUT_DELETE: "prescription_layout.delete",
  PRESCRIPTION_LAYOUT_SET_DEFAULT: "prescription_layout.set_default",
  PRESCRIPTION_LAYOUT_RESET: "prescription_layout.reset",
  PROFESSIONAL_CREATE: "professional.create",
  PROFESSIONAL_UPDATE: "professional.update",
  PROFESSIONAL_DELETE: "professional.delete",
  PROFESSIONAL_INVITE_PROFILE_UPDATE: "professional.invite_profile_update",
} as const

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS]

export const AUDIT_ENTITY_TYPES = {
  PATIENT: "patient",
  APPOINTMENT: "appointment",
  CLINIC: "clinic",
  CLINIC_HOURS: "clinic_hours",
  MEMBER: "member",
  INVITATION: "invitation",
  CHARGE: "charge",
  CLINICAL_NOTE: "clinical_note",
  VITAL_SIGNS: "vital_signs",
  CLINICAL_ALERT: "clinical_alert",
  PRESCRIPTION: "prescription",
  PRESCRIPTION_LAYOUT: "prescription_layout",
  PROFESSIONAL: "professional",
} as const

export type AuditEntityType =
  (typeof AUDIT_ENTITY_TYPES)[keyof typeof AUDIT_ENTITY_TYPES]

export const AUDIT_ACTION_LABELS: Record<string, string> = {
  [AUDIT_ACTIONS.PATIENT_CREATE]: "Paciente criado",
  [AUDIT_ACTIONS.PATIENT_UPDATE]: "Paciente atualizado",
  [AUDIT_ACTIONS.PATIENT_DELETE]: "Paciente excluído",
  [AUDIT_ACTIONS.APPOINTMENT_CREATE]: "Agendamento criado",
  [AUDIT_ACTIONS.APPOINTMENT_RESCHEDULE]: "Agendamento remarcado",
  [AUDIT_ACTIONS.APPOINTMENT_UPDATE]: "Agendamento atualizado",
  [AUDIT_ACTIONS.APPOINTMENT_STATUS_UPDATE]: "Status do agendamento alterado",
  [AUDIT_ACTIONS.APPOINTMENT_CANCEL]: "Agendamento cancelado",
  [AUDIT_ACTIONS.CLINIC_CREATE]: "Clínica criada",
  [AUDIT_ACTIONS.CLINIC_UPDATE]: "Clínica atualizada",
  [AUDIT_ACTIONS.CLINIC_DELETE]: "Clínica excluída",
  [AUDIT_ACTIONS.CLINIC_HOURS_UPSERT]: "Horários atualizados",
  [AUDIT_ACTIONS.MEMBER_ROLE_UPDATE]: "Papel do membro alterado",
  [AUDIT_ACTIONS.MEMBER_REMOVE]: "Membro removido",
  [AUDIT_ACTIONS.MEMBER_STATUS_UPDATE]: "Status do membro alterado",
  [AUDIT_ACTIONS.INVITATION_CREATE]: "Convite enviado",
  [AUDIT_ACTIONS.INVITATION_REVOKE]: "Convite cancelado",
  [AUDIT_ACTIONS.INVITATION_ACCEPT]: "Convite aceito",
  [AUDIT_ACTIONS.CHARGE_CREATE]: "Cobrança criada",
  [AUDIT_ACTIONS.CHARGE_MARK_PAID]: "Cobrança marcada como paga",
  [AUDIT_ACTIONS.CHARGE_CANCEL]: "Cobrança cancelada",
  [AUDIT_ACTIONS.CLINICAL_NOTE_UPSERT]: "Anotação clínica salva",
  [AUDIT_ACTIONS.VITAL_SIGNS_UPSERT]: "Sinais vitais salvos",
  [AUDIT_ACTIONS.CLINICAL_ALERT_CREATE]: "Alerta clínico criado",
  [AUDIT_ACTIONS.CLINICAL_ALERT_DELETE]: "Alerta clínico excluído",
  [AUDIT_ACTIONS.PRESCRIPTION_CREATE]: "Receita criada",
  [AUDIT_ACTIONS.PRESCRIPTION_UPDATE]: "Receita atualizada",
  [AUDIT_ACTIONS.PRESCRIPTION_ISSUE]: "Receita emitida",
  [AUDIT_ACTIONS.PRESCRIPTION_DELETE]: "Receita excluída",
  [AUDIT_ACTIONS.PRESCRIPTION_LAYOUT_UPSERT]: "Modelo de receita salvo",
  [AUDIT_ACTIONS.PRESCRIPTION_LAYOUT_CREATE]: "Modelo de receita criado",
  [AUDIT_ACTIONS.PRESCRIPTION_LAYOUT_UPDATE]: "Modelo de receita atualizado",
  [AUDIT_ACTIONS.PRESCRIPTION_LAYOUT_DELETE]: "Modelo de receita excluído",
  [AUDIT_ACTIONS.PRESCRIPTION_LAYOUT_SET_DEFAULT]:
    "Modelo de receita definido como padrão",
  [AUDIT_ACTIONS.PRESCRIPTION_LAYOUT_RESET]: "Modelos de receita restaurados",
  [AUDIT_ACTIONS.PROFESSIONAL_CREATE]: "Profissional criado",
  [AUDIT_ACTIONS.PROFESSIONAL_UPDATE]: "Profissional atualizado",
  [AUDIT_ACTIONS.PROFESSIONAL_DELETE]: "Profissional excluído",
  [AUDIT_ACTIONS.PROFESSIONAL_INVITE_PROFILE_UPDATE]:
    "Perfil do profissional (convite) atualizado",
}

export const AUDIT_ENTITY_LABELS: Record<string, string> = {
  [AUDIT_ENTITY_TYPES.PATIENT]: "Paciente",
  [AUDIT_ENTITY_TYPES.APPOINTMENT]: "Agendamento",
  [AUDIT_ENTITY_TYPES.CLINIC]: "Clínica",
  [AUDIT_ENTITY_TYPES.CLINIC_HOURS]: "Horários",
  [AUDIT_ENTITY_TYPES.MEMBER]: "Membro",
  [AUDIT_ENTITY_TYPES.INVITATION]: "Convite",
  [AUDIT_ENTITY_TYPES.CHARGE]: "Cobrança",
  [AUDIT_ENTITY_TYPES.CLINICAL_NOTE]: "Anotação clínica",
  [AUDIT_ENTITY_TYPES.VITAL_SIGNS]: "Sinais vitais",
  [AUDIT_ENTITY_TYPES.CLINICAL_ALERT]: "Alerta clínico",
  [AUDIT_ENTITY_TYPES.PRESCRIPTION]: "Receita",
  [AUDIT_ENTITY_TYPES.PRESCRIPTION_LAYOUT]: "Modelo de receita",
  [AUDIT_ENTITY_TYPES.PROFESSIONAL]: "Profissional",
}
